#!/bin/sh 
cd ${0%/*} || exit 1 

. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp -r ../combustorMesh/processor? . 

runApplication reconstructParMesh -latestTime -constant

runApplication decomposePar -force 

runParallel checkMesh 

runParallel renumberMesh -overwrite 

runParallel $(getApplication)

runApplication reconstructPar -noZero

runApplication foamToVTK -useTimeName
