#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# remove post-processing files
rm -f initialConditions-cmb.tar.gz log*
rm -rf postProcessing

cleanCase

#------------------------------------------------------------------------------
