#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh

runApplication mapFields ../combustorRhoPimple/ -case . -sourceTime 0.5 -parallelSource

runApplication decomposePar

runParallel checkMesh

runParallel renumberMesh -overwrite

runParallel reactingFoam

runApplication reconstructPar 

runApplication foamToVTK

# ----------------------------------------------------------------- end-of-file
