#!/bin/sh
cd ${0%/*} || exit 1 

. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp -r ../combustorMesh/processor? . 

runApplication reconstructParMesh -latestTime -constant

runApplication mapFields ../combustorRhoPimple -case . -sourceTime latestTime -parallelSource -consistent -noFunctionObjects

runApplication chemkinToFoam chemkin/chem.inp chemkin/therm.dat chemkin/transportProperties constant/reactions constant/speciesThermo

paraFoam -touch 

runApplication decomposePar -force 

runParallel checkMesh 

runParallel renumberMesh -overwrite 

runParallel $(getApplication)

runApplication reconstructPar -withZero

runApplication foamToVTK -useTimeName
